
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.proyectocompiladores;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int ELIMINAR = 34;
  public static final int PUNTO_Y_COMA = 28;
  public static final int DEVOLVER = 10;
  public static final int LOGARITMO = 52;
  public static final int RESTA = 38;
  public static final int DESDE = 15;
  public static final int DOS_PUNTOS = 27;
  public static final int CADENA_A_BOOLEANO = 54;
  public static final int ENTONCES = 6;
  public static final int DECREMENTAR = 48;
  public static final int INSTANCIAR = 14;
  public static final int INCREMENTAR = 47;
  public static final int PRINCIPAL = 13;
  public static final int AND = 25;
  public static final int IGUAL = 24;
  public static final int SIGNOS = 58;
  public static final int DISTINTO_QUE = 45;
  public static final int SINO = 7;
  public static final int OR = 26;
  public static final int MIENTRAS = 16;
  public static final int EXTIENDE = 20;
  public static final int RAIZ = 30;
  public static final int ESCRIBIR = 9;
  public static final int DESTRUCTOR = 12;
  public static final int TIPO_DE_METODOS = 53;
  public static final int INCREMENTO = 17;
  public static final int SUMA = 37;
  public static final int IF = 5;
  public static final int PARENTESIS2 = 22;
  public static final int PARENTESIS1 = 21;
  public static final int EOF = 0;
  public static final int PROPIEDADES = 3;
  public static final int CLASE = 2;
  public static final int NEW = 67;
  public static final int DECREMENTO = 18;
  public static final int error = 1;
  public static final int COMA = 23;
  public static final int CADENA = 57;
  public static final int COMENTARIO = 61;
  public static final int MODULO = 42;
  public static final int MENOS = 31;
  public static final int OPERADORES = 36;
  public static final int MAYOR_QUE = 44;
  public static final int TIPO_DATO = 35;
  public static final int VARIABLE_CLASE = 33;
  public static final int FUNCION_ESPECIAL = 59;
  public static final int NUMERO_DECIMAL = 64;
  public static final int METODOS = 4;
  public static final int TANGENTE = 51;
  public static final int PUNTO = 32;
  public static final int COSENO = 50;
  public static final int VARIABLE = 29;
  public static final int CADENA_A_ENTERO = 56;
  public static final int CADENA_A_REAL = 55;
  public static final int IGUAL_QUE = 46;
  public static final int SENO = 49;
  public static final int CONSTRUCTOR = 11;
  public static final int FALSO = 66;
  public static final int FUNCIONES_CLICLOS_ETC = 60;
  public static final int EXPONENCIACION = 41;
  public static final int LEER = 8;
  public static final int HACER = 19;
  public static final int SALTO_LINEA = 62;
  public static final int VERDADERO = 65;
  public static final int MENOR_QUE = 43;
  public static final int DIVISION = 40;
  public static final int EJECUTAR = 63;
  public static final int MULTIPLICACION = 39;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASE",
  "PROPIEDADES",
  "METODOS",
  "IF",
  "ENTONCES",
  "SINO",
  "LEER",
  "ESCRIBIR",
  "DEVOLVER",
  "CONSTRUCTOR",
  "DESTRUCTOR",
  "PRINCIPAL",
  "INSTANCIAR",
  "DESDE",
  "MIENTRAS",
  "INCREMENTO",
  "DECREMENTO",
  "HACER",
  "EXTIENDE",
  "PARENTESIS1",
  "PARENTESIS2",
  "COMA",
  "IGUAL",
  "AND",
  "OR",
  "DOS_PUNTOS",
  "PUNTO_Y_COMA",
  "VARIABLE",
  "RAIZ",
  "MENOS",
  "PUNTO",
  "VARIABLE_CLASE",
  "ELIMINAR",
  "TIPO_DATO",
  "OPERADORES",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "EXPONENCIACION",
  "MODULO",
  "MENOR_QUE",
  "MAYOR_QUE",
  "DISTINTO_QUE",
  "IGUAL_QUE",
  "INCREMENTAR",
  "DECREMENTAR",
  "SENO",
  "COSENO",
  "TANGENTE",
  "LOGARITMO",
  "TIPO_DE_METODOS",
  "CADENA_A_BOOLEANO",
  "CADENA_A_REAL",
  "CADENA_A_ENTERO",
  "CADENA",
  "SIGNOS",
  "FUNCION_ESPECIAL",
  "FUNCIONES_CLICLOS_ETC",
  "COMENTARIO",
  "SALTO_LINEA",
  "EJECUTAR",
  "NUMERO_DECIMAL",
  "VERDADERO",
  "FALSO",
  "NEW"
  };
}

