// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/main/java/com/mycompany/proyectocompiladores/Lexemas.flex

package com.mycompany.proyectocompiladores;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;
import java_cup.runtime.Symbol;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Testeo implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\5\1\6"+
    "\1\7\2\0\1\10\2\0\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\11\22\1\23\1\0"+
    "\1\24\1\25\1\26\2\0\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\2\35\1\36\3\35\1\37\1\40\1\41"+
    "\1\42\1\35\1\43\3\35\1\34\4\35\1\44\1\0"+
    "\1\45\1\0\1\46\1\0\1\47\1\50\1\51\1\52"+
    "\1\53\1\54\1\55\1\56\1\57\1\60\1\61\1\62"+
    "\1\63\1\64\1\65\1\66\1\61\1\67\1\70\1\71"+
    "\1\72\1\73\1\61\1\74\1\61\1\75\1\0\1\76"+
    "\10\0\1\3\105\0\1\77\u0154\0\1\100\7\0\2\3"+
    "\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\3\1\4\2\1\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\2\16"+
    "\1\17\1\20\1\21\1\22\5\23\1\24\4\23\1\25"+
    "\1\26\1\24\2\27\2\24\4\27\1\24\3\27\2\24"+
    "\2\27\1\24\1\1\1\0\1\30\1\0\1\31\1\32"+
    "\1\33\2\0\1\34\2\0\1\35\1\23\1\0\7\23"+
    "\1\36\3\23\1\37\24\27\1\40\2\27\1\41\1\0"+
    "\1\42\2\0\2\34\1\43\10\23\1\44\3\23\34\27"+
    "\1\0\1\34\13\23\21\27\1\45\3\27\1\46\1\27"+
    "\1\47\1\50\1\51\1\52\2\27\1\53\12\23\2\27"+
    "\1\53\2\27\1\54\6\27\1\55\1\56\5\27\1\57"+
    "\3\27\12\23\1\27\1\60\1\61\3\27\1\62\13\27"+
    "\4\23\1\63\1\23\1\64\3\23\10\27\1\65\7\27"+
    "\2\23\1\66\1\67\3\23\1\70\4\27\1\71\1\66"+
    "\1\72\1\73\1\74\3\27\1\75\1\27\1\76\1\27"+
    "\2\23\1\77\1\23\6\27\1\100\1\27\1\101\1\23"+
    "\1\102\1\23\5\27\1\103\1\27\1\104\1\105\2\27"+
    "\1\106\1\107\1\110\1\105\3\27\1\111\1\112";

  private static int [] zzUnpackAction() {
    int [] result = new int[341];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\101\0\101\0\101\0\202\0\303\0\u0104\0\u0145"+
    "\0\101\0\101\0\101\0\101\0\u0186\0\101\0\u01c7\0\u0208"+
    "\0\u0249\0\u028a\0\u02cb\0\101\0\101\0\u030c\0\101\0\u034d"+
    "\0\u038e\0\u03cf\0\u0410\0\u0451\0\u038e\0\u0492\0\u04d3\0\u0514"+
    "\0\u0555\0\101\0\101\0\u0596\0\u05d7\0\u0618\0\u0659\0\u069a"+
    "\0\u06db\0\u0596\0\u071c\0\u075d\0\u079e\0\u07df\0\u0820\0\u0861"+
    "\0\u08a2\0\u08e3\0\u0924\0\u0965\0\101\0\u09a6\0\u09e7\0\101"+
    "\0\u0145\0\101\0\101\0\101\0\u0a28\0\u0a69\0\u0aaa\0\u0208"+
    "\0\u028a\0\101\0\u0aeb\0\u0b2c\0\u0b6d\0\u0bae\0\u0bef\0\u0c30"+
    "\0\u0c71\0\u0cb2\0\u0cf3\0\u038e\0\u0d34\0\u0d75\0\u0db6\0\u0df7"+
    "\0\u0e38\0\u0e79\0\u0eba\0\u0efb\0\u0f3c\0\u0f7d\0\u0fbe\0\u0fff"+
    "\0\u1040\0\u1081\0\u10c2\0\u1103\0\u1144\0\u1185\0\u11c6\0\u1207"+
    "\0\u1248\0\u1289\0\u12ca\0\u130b\0\u134c\0\u138d\0\u13ce\0\101"+
    "\0\u140f\0\u0a28\0\u1450\0\u1491\0\101\0\u14d2\0\u038e\0\u0b2c"+
    "\0\u1513\0\u1554\0\u1595\0\u15d6\0\u1617\0\u1658\0\u1699\0\u038e"+
    "\0\u16da\0\u171b\0\u175c\0\u0df7\0\u179d\0\u17de\0\u181f\0\u1860"+
    "\0\u18a1\0\u18e2\0\u1923\0\u1964\0\u19a5\0\u19e6\0\u1a27\0\u1a68"+
    "\0\u1aa9\0\u1aea\0\u1b2b\0\u1b6c\0\u1bad\0\u1bee\0\u1c2f\0\u1c70"+
    "\0\u1cb1\0\u1cf2\0\u1d33\0\u1d74\0\u1db5\0\u1df6\0\u1e37\0\u1e78"+
    "\0\u1450\0\u1eb9\0\u1efa\0\u1f3b\0\u1f7c\0\u1fbd\0\u1ffe\0\u203f"+
    "\0\u2080\0\u20c1\0\u2102\0\u2143\0\u2184\0\u21c5\0\u2206\0\u2247"+
    "\0\u2288\0\u22c9\0\u230a\0\u234b\0\u238c\0\u23cd\0\u240e\0\u244f"+
    "\0\u2490\0\u24d1\0\u2512\0\u2553\0\u2594\0\u0596\0\u25d5\0\u2616"+
    "\0\u2657\0\u0596\0\u2698\0\u0596\0\u0596\0\u0596\0\u0596\0\u26d9"+
    "\0\u271a\0\u038e\0\u275b\0\u279c\0\u27dd\0\u281e\0\u285f\0\u28a0"+
    "\0\u28e1\0\u2922\0\u2963\0\u29a4\0\u29e5\0\u2a26\0\u0596\0\u2a67"+
    "\0\u2aa8\0\u0596\0\u2ae9\0\u2b2a\0\u2b6b\0\u2bac\0\u2bed\0\u2c2e"+
    "\0\u0596\0\u0596\0\u2c6f\0\u2cb0\0\u2cf1\0\u2d32\0\u2d73\0\u0596"+
    "\0\u2db4\0\u2df5\0\u2e36\0\u2e77\0\u2eb8\0\u2ef9\0\u2f3a\0\u2f7b"+
    "\0\u2fbc\0\u2ffd\0\u303e\0\u307f\0\u30c0\0\u3101\0\u3142\0\u0596"+
    "\0\u3183\0\u31c4\0\u3205\0\u0596\0\u3246\0\u3287\0\u32c8\0\u3309"+
    "\0\u334a\0\u338b\0\u33cc\0\u340d\0\u344e\0\u348f\0\u34d0\0\u3511"+
    "\0\u3552\0\u3593\0\u35d4\0\u038e\0\u3615\0\u038e\0\u3656\0\u3697"+
    "\0\u36d8\0\u3719\0\u375a\0\u379b\0\u37dc\0\u381d\0\u385e\0\u389f"+
    "\0\u38e0\0\u0596\0\u3921\0\u3962\0\u39a3\0\u39e4\0\u3a25\0\u3a66"+
    "\0\u3aa7\0\u3ae8\0\u3b29\0\u038e\0\u038e\0\u3b6a\0\u3bab\0\u3bec"+
    "\0\u0596\0\u3c2d\0\u3c6e\0\u3caf\0\u3cf0\0\u0596\0\u0596\0\u0596"+
    "\0\u0596\0\u0596\0\u3d31\0\u3d72\0\u3db3\0\u0596\0\u3df4\0\u0596"+
    "\0\u3e35\0\u3e76\0\u3eb7\0\u038e\0\u3ef8\0\u3f39\0\u3f7a\0\u3fbb"+
    "\0\u3ffc\0\u403d\0\u407e\0\u0596\0\u40bf\0\u0596\0\u4100\0\u038e"+
    "\0\u4141\0\u4182\0\u41c3\0\u4204\0\u4245\0\u4286\0\u0596\0\u42c7"+
    "\0\u038e\0\u038e\0\u4308\0\u4349\0\u0596\0\u0596\0\u0596\0\u0596"+
    "\0\u438a\0\u43cb\0\u440c\0\u0596\0\u0596";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[341];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\0\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\31\1\36\1\37"+
    "\1\31\1\40\1\41\1\31\1\42\1\43\1\2\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\52\1\53\1\54"+
    "\2\52\1\55\1\56\1\57\1\44\1\60\1\61\1\62"+
    "\1\63\1\52\1\64\2\52\1\65\1\66\1\2\103\0"+
    "\1\4\103\0\1\67\120\0\1\70\60\0\1\71\1\0"+
    "\1\72\11\0\2\71\4\0\15\71\3\0\27\71\17\0"+
    "\1\73\102\0\1\74\103\0\2\75\71\0\1\76\4\0"+
    "\1\77\77\0\1\100\1\0\2\101\75\0\1\100\1\0"+
    "\2\23\103\0\1\102\74\0\2\31\4\0\11\31\1\103"+
    "\3\31\2\0\1\104\30\31\23\0\2\31\4\0\15\31"+
    "\2\0\1\104\30\31\23\0\2\31\4\0\15\31\2\0"+
    "\1\104\13\31\1\105\2\31\1\106\11\31\23\0\2\31"+
    "\4\0\15\31\2\0\1\104\4\31\1\107\23\31\23\0"+
    "\2\31\4\0\15\31\2\0\1\104\11\31\1\110\1\31"+
    "\1\111\14\31\23\0\2\31\4\0\15\31\2\0\1\104"+
    "\14\31\1\112\13\31\23\0\2\31\4\0\15\31\2\0"+
    "\1\104\4\31\1\113\23\31\23\0\2\31\4\0\14\31"+
    "\1\114\2\0\1\104\30\31\23\0\2\31\4\0\15\31"+
    "\2\0\1\104\1\115\17\31\1\116\2\31\1\117\4\31"+
    "\23\0\2\52\4\0\15\52\2\0\1\120\30\52\23\0"+
    "\2\52\4\0\15\52\2\0\1\120\16\52\1\121\11\52"+
    "\23\0\2\52\4\0\15\52\2\0\1\120\1\122\12\52"+
    "\1\123\2\52\1\124\11\52\23\0\2\52\4\0\15\52"+
    "\2\0\1\120\4\52\1\125\23\52\23\0\2\52\4\0"+
    "\15\52\2\0\1\120\11\52\1\126\3\52\1\127\3\52"+
    "\1\130\3\52\1\131\2\52\23\0\2\52\4\0\15\52"+
    "\2\0\1\120\1\132\27\52\23\0\2\52\4\0\15\52"+
    "\2\0\1\120\1\133\27\52\23\0\2\52\4\0\15\52"+
    "\2\0\1\120\15\52\1\134\12\52\23\0\2\52\4\0"+
    "\15\52\2\0\1\120\4\52\1\135\11\52\1\136\11\52"+
    "\23\0\2\52\4\0\15\52\2\0\1\120\10\52\1\137"+
    "\17\52\23\0\2\52\4\0\15\52\2\0\1\120\23\52"+
    "\1\140\4\52\23\0\2\52\4\0\15\52\2\0\1\120"+
    "\20\52\1\141\7\52\23\0\2\52\4\0\15\52\2\0"+
    "\1\120\1\142\3\52\1\143\23\52\23\0\2\52\4\0"+
    "\15\52\2\0\1\120\4\52\1\144\3\52\1\145\17\52"+
    "\23\0\2\52\4\0\15\52\2\0\1\120\1\146\27\52"+
    "\23\0\2\52\4\0\15\52\2\0\1\120\4\52\1\147"+
    "\23\52\102\0\1\150\5\0\1\151\114\0\1\75\1\152"+
    "\56\0\13\153\1\154\65\153\2\77\1\155\1\77\1\156"+
    "\74\77\21\0\2\31\4\0\3\31\1\157\11\31\2\0"+
    "\1\104\30\31\23\0\2\160\4\0\15\160\3\0\30\160"+
    "\23\0\2\31\4\0\15\31\2\0\1\104\1\161\27\31"+
    "\23\0\2\31\4\0\15\31\2\0\1\104\15\31\1\162"+
    "\12\31\23\0\2\31\4\0\15\31\2\0\1\104\21\31"+
    "\1\163\6\31\23\0\2\31\4\0\15\31\2\0\1\104"+
    "\4\31\1\164\23\31\23\0\2\31\4\0\15\31\2\0"+
    "\1\104\10\31\1\165\17\31\23\0\2\31\4\0\15\31"+
    "\2\0\1\104\17\31\1\166\10\31\23\0\2\31\4\0"+
    "\15\31\2\0\1\104\22\31\1\167\5\31\23\0\2\31"+
    "\4\0\15\31\2\0\1\104\20\31\1\170\7\31\23\0"+
    "\2\31\4\0\15\31\2\0\1\104\10\31\1\171\5\31"+
    "\1\172\11\31\23\0\2\31\4\0\15\31\2\0\1\104"+
    "\1\31\1\173\26\31\23\0\2\174\4\0\15\174\3\0"+
    "\30\174\23\0\2\52\4\0\15\52\2\0\1\120\16\52"+
    "\1\175\11\52\23\0\2\52\4\0\15\52\2\0\1\120"+
    "\3\52\1\176\24\52\23\0\2\52\4\0\15\52\2\0"+
    "\1\120\1\177\27\52\23\0\2\52\4\0\15\52\2\0"+
    "\1\120\21\52\1\200\6\52\23\0\2\52\4\0\15\52"+
    "\2\0\1\120\2\52\1\201\16\52\1\202\2\52\1\203"+
    "\3\52\23\0\2\52\4\0\15\52\2\0\1\120\4\52"+
    "\1\204\23\52\23\0\2\52\4\0\15\52\2\0\1\120"+
    "\22\52\1\205\5\52\23\0\2\52\4\0\15\52\2\0"+
    "\1\120\2\52\1\206\25\52\23\0\2\52\4\0\15\52"+
    "\2\0\1\120\22\52\1\207\5\52\23\0\2\52\4\0"+
    "\15\52\2\0\1\120\13\52\1\210\14\52\23\0\2\52"+
    "\4\0\15\52\2\0\1\120\2\52\1\211\25\52\23\0"+
    "\2\52\4\0\15\52\2\0\1\120\2\52\1\212\16\52"+
    "\1\213\6\52\23\0\2\52\4\0\15\52\2\0\1\120"+
    "\4\52\1\214\23\52\23\0\2\52\4\0\15\52\2\0"+
    "\1\120\6\52\1\215\21\52\23\0\2\52\4\0\15\52"+
    "\2\0\1\120\4\52\1\216\23\52\23\0\2\52\4\0"+
    "\15\52\2\0\1\120\4\52\1\217\6\52\1\220\14\52"+
    "\23\0\2\52\4\0\15\52\2\0\1\120\16\52\1\221"+
    "\11\52\23\0\2\52\4\0\15\52\2\0\1\120\10\52"+
    "\1\222\17\52\23\0\2\52\4\0\15\52\2\0\1\120"+
    "\1\223\27\52\23\0\2\52\4\0\15\52\2\0\1\120"+
    "\15\52\1\224\12\52\23\0\2\52\4\0\15\52\2\0"+
    "\1\120\15\52\1\225\12\52\23\0\2\52\4\0\15\52"+
    "\2\0\1\120\15\52\1\226\12\52\23\0\2\52\4\0"+
    "\15\52\2\0\1\120\20\52\1\227\7\52\7\0\1\3"+
    "\73\0\13\153\1\230\100\153\1\230\4\153\1\231\60\153"+
    "\2\0\1\155\117\0\2\31\4\0\15\31\2\0\1\104"+
    "\21\31\1\232\6\31\23\0\2\31\4\0\15\31\2\0"+
    "\1\104\21\31\1\233\6\31\23\0\2\31\4\0\15\31"+
    "\2\0\1\104\22\31\1\234\5\31\23\0\2\31\4\0"+
    "\15\31\2\0\1\104\2\31\1\235\25\31\23\0\2\31"+
    "\4\0\15\31\2\0\1\104\14\31\1\236\13\31\23\0"+
    "\2\31\4\0\15\31\2\0\1\104\1\115\27\31\23\0"+
    "\2\31\4\0\15\31\2\0\1\104\16\31\1\237\11\31"+
    "\23\0\2\31\4\0\15\31\2\0\1\104\15\31\1\240"+
    "\6\31\1\241\3\31\23\0\2\31\4\0\15\31\2\0"+
    "\1\104\17\31\1\242\2\31\1\243\5\31\23\0\2\31"+
    "\4\0\15\31\2\0\1\104\13\31\1\244\14\31\23\0"+
    "\2\52\4\0\15\52\2\0\1\120\13\52\1\245\14\52"+
    "\23\0\2\52\4\0\15\52\2\0\1\120\4\52\1\246"+
    "\23\52\23\0\2\52\4\0\15\52\2\0\1\120\21\52"+
    "\1\247\6\52\23\0\2\52\4\0\15\52\2\0\1\120"+
    "\4\52\1\250\23\52\23\0\2\52\4\0\15\52\2\0"+
    "\1\120\20\52\1\251\7\52\23\0\2\52\4\0\15\52"+
    "\2\0\1\120\3\52\1\252\24\52\23\0\2\52\4\0"+
    "\15\52\2\0\1\120\16\52\1\253\11\52\23\0\2\52"+
    "\4\0\15\52\2\0\1\120\2\52\1\254\25\52\23\0"+
    "\2\52\4\0\15\52\2\0\1\120\4\52\1\255\11\52"+
    "\1\256\11\52\23\0\2\52\4\0\15\52\2\0\1\120"+
    "\20\52\1\257\7\52\23\0\2\52\4\0\15\52\2\0"+
    "\1\120\10\52\1\260\17\52\23\0\2\52\4\0\15\52"+
    "\2\0\1\120\21\52\1\261\6\52\23\0\2\52\4\0"+
    "\15\52\2\0\1\120\4\52\1\262\23\52\23\0\2\52"+
    "\4\0\15\52\2\0\1\120\13\52\1\263\4\52\1\264"+
    "\7\52\23\0\2\52\4\0\15\52\2\0\1\120\22\52"+
    "\1\265\5\52\23\0\2\52\4\0\15\52\2\0\1\120"+
    "\20\52\1\266\7\52\23\0\2\52\4\0\15\52\2\0"+
    "\1\120\1\267\27\52\23\0\2\52\4\0\15\52\2\0"+
    "\1\120\15\52\1\270\12\52\23\0\2\52\4\0\15\52"+
    "\2\0\1\120\24\52\1\271\3\52\23\0\2\52\4\0"+
    "\15\52\2\0\1\120\16\52\1\272\11\52\23\0\2\52"+
    "\4\0\15\52\2\0\1\120\17\52\1\273\10\52\23\0"+
    "\2\52\4\0\15\52\2\0\1\120\26\52\1\274\1\52"+
    "\23\0\2\52\4\0\15\52\2\0\1\120\13\52\1\275"+
    "\14\52\23\0\2\52\4\0\15\52\2\0\1\120\16\52"+
    "\1\276\11\52\23\0\2\52\4\0\15\52\2\0\1\120"+
    "\16\52\1\277\11\52\23\0\2\52\4\0\15\52\2\0"+
    "\1\120\6\52\1\300\21\52\23\0\2\52\4\0\15\52"+
    "\2\0\1\120\3\52\1\301\24\52\2\0\13\153\1\230"+
    "\4\153\1\155\60\153\21\0\2\31\4\0\15\31\2\0"+
    "\1\104\4\31\1\302\23\31\23\0\2\31\4\0\15\31"+
    "\2\0\1\104\22\31\1\303\5\31\23\0\2\31\4\0"+
    "\15\31\2\0\1\104\20\31\1\304\7\31\23\0\2\31"+
    "\4\0\15\31\2\0\1\104\23\31\1\305\4\31\23\0"+
    "\2\31\4\0\15\31\2\0\1\104\10\31\1\306\17\31"+
    "\23\0\2\31\4\0\15\31\2\0\1\104\3\31\1\307"+
    "\24\31\23\0\2\31\4\0\15\31\2\0\1\104\2\31"+
    "\1\310\25\31\23\0\2\31\4\0\15\31\2\0\1\104"+
    "\1\311\27\31\23\0\2\31\4\0\15\31\2\0\1\104"+
    "\10\31\1\312\17\31\23\0\2\31\4\0\15\31\2\0"+
    "\1\104\4\31\1\313\23\31\23\0\2\31\4\0\15\31"+
    "\2\0\1\104\10\31\1\314\17\31\23\0\2\52\4\0"+
    "\15\52\2\0\1\120\4\52\1\315\23\52\23\0\2\52"+
    "\4\0\15\52\2\0\1\120\15\52\1\316\12\52\23\0"+
    "\2\52\4\0\15\52\2\0\1\120\4\52\1\317\23\52"+
    "\23\0\2\52\4\0\15\52\2\0\1\120\15\52\1\320"+
    "\12\52\23\0\2\52\4\0\15\52\2\0\1\120\4\52"+
    "\1\321\23\52\23\0\2\52\4\0\15\52\2\0\1\120"+
    "\4\52\1\322\23\52\23\0\2\52\4\0\15\52\2\0"+
    "\1\120\13\52\1\323\14\52\23\0\2\52\4\0\15\52"+
    "\2\0\1\120\23\52\1\324\4\52\23\0\2\52\4\0"+
    "\15\52\2\0\1\120\20\52\1\325\7\52\23\0\2\52"+
    "\4\0\15\52\2\0\1\120\15\52\1\326\12\52\23\0"+
    "\2\52\4\0\15\52\2\0\1\120\10\52\1\327\17\52"+
    "\23\0\2\52\4\0\15\52\2\0\1\120\4\52\1\330"+
    "\23\52\23\0\2\52\4\0\15\52\2\0\1\120\16\52"+
    "\1\331\11\52\23\0\2\52\4\0\15\52\2\0\1\120"+
    "\20\52\1\332\7\52\23\0\2\52\4\0\15\52\2\0"+
    "\1\120\23\52\1\333\4\52\23\0\2\52\4\0\15\52"+
    "\2\0\1\120\4\52\1\334\23\52\23\0\2\52\4\0"+
    "\15\52\2\0\1\120\1\335\27\52\23\0\2\52\4\0"+
    "\15\52\2\0\1\120\20\52\1\336\7\52\23\0\2\52"+
    "\4\0\15\52\2\0\1\120\22\52\1\337\5\52\23\0"+
    "\2\52\4\0\15\52\2\0\1\120\16\52\1\340\11\52"+
    "\23\0\2\52\4\0\15\52\2\0\1\120\10\52\1\341"+
    "\17\52\23\0\2\52\4\0\15\52\2\0\1\120\4\52"+
    "\1\342\23\52\23\0\2\52\4\0\15\52\2\0\1\120"+
    "\1\343\27\52\23\0\2\31\4\0\15\31\2\0\1\104"+
    "\20\31\1\344\7\31\23\0\2\31\4\0\15\31\2\0"+
    "\1\104\23\31\1\345\4\31\23\0\2\31\4\0\15\31"+
    "\2\0\1\104\22\31\1\346\5\31\23\0\2\31\4\0"+
    "\15\31\2\0\1\104\15\31\1\347\12\31\23\0\2\31"+
    "\4\0\15\31\2\0\1\104\16\31\1\350\11\31\23\0"+
    "\2\31\4\0\15\31\2\0\1\104\10\31\1\351\17\31"+
    "\23\0\2\31\4\0\15\31\2\0\1\104\3\31\1\352"+
    "\24\31\23\0\2\31\4\0\15\31\2\0\1\104\4\31"+
    "\1\353\23\31\23\0\2\31\4\0\15\31\2\0\1\104"+
    "\6\31\1\354\21\31\23\0\2\31\4\0\15\31\2\0"+
    "\1\104\2\31\1\355\25\31\23\0\2\52\4\0\15\52"+
    "\2\0\1\120\1\356\27\52\23\0\2\52\4\0\15\52"+
    "\2\0\1\120\1\357\27\52\23\0\2\52\4\0\15\52"+
    "\2\0\1\120\16\52\1\360\11\52\23\0\2\52\4\0"+
    "\15\52\2\0\1\120\14\52\1\361\13\52\23\0\2\52"+
    "\4\0\15\52\2\0\1\120\24\52\1\362\3\52\23\0"+
    "\2\52\4\0\15\52\2\0\1\120\22\52\1\363\5\52"+
    "\23\0\2\52\4\0\15\52\2\0\1\120\16\52\1\364"+
    "\11\52\23\0\2\52\4\0\15\52\2\0\1\120\2\52"+
    "\1\365\25\52\23\0\2\52\4\0\15\52\2\0\1\120"+
    "\1\52\1\366\26\52\23\0\2\52\4\0\15\52\2\0"+
    "\1\120\15\52\1\367\12\52\23\0\2\52\4\0\15\52"+
    "\2\0\1\120\10\52\1\370\17\52\23\0\2\52\4\0"+
    "\15\52\2\0\1\120\14\52\1\371\13\52\23\0\2\52"+
    "\4\0\15\52\2\0\1\120\15\52\1\372\12\52\23\0"+
    "\2\52\4\0\15\52\2\0\1\120\10\52\1\373\17\52"+
    "\23\0\2\52\4\0\15\52\2\0\1\120\20\52\1\374"+
    "\7\52\23\0\2\52\4\0\15\52\2\0\1\120\4\52"+
    "\1\375\23\52\23\0\2\52\4\0\15\52\2\0\1\120"+
    "\15\52\1\376\12\52\23\0\2\52\4\0\15\52\2\0"+
    "\1\120\3\52\1\377\24\52\23\0\2\31\4\0\15\31"+
    "\2\0\1\104\23\31\1\u0100\4\31\23\0\2\31\4\0"+
    "\15\31\2\0\1\104\2\31\1\u0101\25\31\23\0\2\31"+
    "\4\0\15\31\2\0\1\104\1\u0102\27\31\23\0\2\31"+
    "\4\0\15\31\2\0\1\104\1\u0103\27\31\23\0\2\31"+
    "\4\0\15\31\2\0\1\104\21\31\1\u0104\6\31\23\0"+
    "\2\31\4\0\15\31\2\0\1\104\17\31\1\u0105\10\31"+
    "\23\0\2\31\4\0\15\31\2\0\1\104\1\u0106\15\31"+
    "\1\u0107\11\31\23\0\2\31\4\0\15\31\2\0\1\104"+
    "\3\31\1\u0108\24\31\23\0\2\31\4\0\15\31\2\0"+
    "\1\104\10\31\1\u0109\17\31\23\0\2\31\4\0\15\31"+
    "\2\0\1\104\1\u0106\15\31\1\u0106\11\31\23\0\2\52"+
    "\4\0\15\52\2\0\1\120\15\52\1\u010a\12\52\23\0"+
    "\2\52\4\0\1\u010b\14\52\2\0\1\120\30\52\23\0"+
    "\2\52\4\0\15\52\2\0\1\120\4\52\1\u010c\23\52"+
    "\23\0\2\52\4\0\15\52\2\0\1\120\4\52\1\u010d"+
    "\23\52\23\0\2\52\4\0\15\52\2\0\1\120\1\u010e"+
    "\27\52\23\0\2\52\4\0\15\52\2\0\1\120\4\52"+
    "\1\u010f\23\52\23\0\2\52\4\0\15\52\2\0\1\120"+
    "\10\52\1\u0110\17\52\23\0\2\52\4\0\15\52\2\0"+
    "\1\120\3\52\1\u0111\24\52\23\0\2\52\4\0\15\52"+
    "\2\0\1\120\20\52\1\u0112\7\52\23\0\2\52\4\0"+
    "\15\52\2\0\1\120\4\52\1\u0113\23\52\23\0\2\52"+
    "\4\0\15\52\2\0\1\120\2\52\1\u0114\25\52\23\0"+
    "\2\52\4\0\15\52\2\0\1\120\22\52\1\u0115\5\52"+
    "\23\0\2\52\4\0\15\52\2\0\1\120\1\u0116\27\52"+
    "\23\0\2\52\4\0\15\52\2\0\1\120\3\52\1\u0117"+
    "\24\52\23\0\2\52\4\0\15\52\2\0\1\120\22\52"+
    "\1\u0118\5\52\23\0\2\52\4\0\15\52\2\0\1\120"+
    "\4\52\1\u0119\23\52\23\0\2\31\4\0\15\31\2\0"+
    "\1\104\2\31\1\u011a\25\31\23\0\2\31\4\0\15\31"+
    "\2\0\1\104\22\31\1\u011b\5\31\23\0\2\31\4\0"+
    "\15\31\2\0\1\104\20\31\1\u011c\7\31\23\0\2\31"+
    "\4\0\15\31\2\0\1\104\20\31\1\u011d\7\31\23\0"+
    "\2\31\4\0\15\31\2\0\1\104\1\u011e\27\31\23\0"+
    "\2\31\4\0\15\31\2\0\1\104\21\31\1\u0106\6\31"+
    "\23\0\2\31\4\0\15\31\2\0\1\104\1\u011f\27\31"+
    "\23\0\2\31\4\0\15\31\2\0\1\104\3\31\1\u0120"+
    "\24\31\23\0\2\52\4\0\15\52\2\0\1\120\16\52"+
    "\1\u0121\11\52\23\0\2\52\4\0\1\52\1\u0122\2\52"+
    "\1\u0123\7\52\1\u0124\2\0\1\120\30\52\23\0\2\52"+
    "\4\0\15\52\2\0\1\120\15\52\1\u0125\12\52\23\0"+
    "\2\52\4\0\15\52\2\0\1\120\20\52\1\u0126\7\52"+
    "\23\0\2\52\4\0\15\52\2\0\1\120\20\52\1\u0127"+
    "\7\52\23\0\2\52\4\0\15\52\2\0\1\120\21\52"+
    "\1\u0128\6\52\23\0\2\52\4\0\15\52\2\0\1\120"+
    "\20\52\1\u0129\7\52\23\0\2\52\4\0\15\52\2\0"+
    "\1\120\4\52\1\u012a\23\52\23\0\2\52\4\0\15\52"+
    "\2\0\1\120\15\52\1\u012b\12\52\23\0\2\52\4\0"+
    "\15\52\2\0\1\120\10\52\1\u012c\17\52\23\0\2\52"+
    "\4\0\15\52\2\0\1\120\14\52\1\u012d\13\52\23\0"+
    "\2\52\4\0\15\52\2\0\1\120\21\52\1\u012e\6\52"+
    "\23\0\2\52\4\0\15\52\2\0\1\120\1\u012f\27\52"+
    "\23\0\2\52\4\0\15\52\2\0\1\120\4\52\1\u0130"+
    "\23\52\23\0\2\52\4\0\15\52\2\0\1\120\20\52"+
    "\1\u0131\7\52\23\0\2\31\4\0\15\31\2\0\1\104"+
    "\22\31\1\u0132\5\31\23\0\2\31\4\0\15\31\2\0"+
    "\1\104\16\31\1\u0133\11\31\23\0\2\31\4\0\15\31"+
    "\2\0\1\104\13\31\1\u0134\14\31\23\0\2\31\4\0"+
    "\15\31\2\0\1\104\3\31\1\u0135\24\31\23\0\2\31"+
    "\4\0\15\31\2\0\1\104\1\u0107\15\31\1\u0107\11\31"+
    "\23\0\2\52\4\0\15\52\2\0\1\120\16\52\1\u0136"+
    "\11\52\23\0\2\52\4\0\15\52\2\0\1\120\15\52"+
    "\1\u0137\12\52\23\0\2\52\4\0\15\52\2\0\1\120"+
    "\4\52\1\u0138\23\52\23\0\2\52\4\0\15\52\2\0"+
    "\1\120\22\52\1\u0139\5\52\23\0\2\52\4\0\15\52"+
    "\2\0\1\120\22\52\1\u013a\5\52\23\0\2\52\4\0"+
    "\15\52\2\0\1\120\1\u013b\27\52\23\0\2\52\4\0"+
    "\15\52\2\0\1\120\16\52\1\u013c\11\52\23\0\2\52"+
    "\4\0\15\52\2\0\1\120\3\52\1\u013d\24\52\23\0"+
    "\2\52\4\0\15\52\2\0\1\120\16\52\1\u013e\11\52"+
    "\23\0\2\31\4\0\15\31\2\0\1\104\16\31\1\u013f"+
    "\11\31\23\0\2\31\4\0\15\31\2\0\1\104\20\31"+
    "\1\u0140\7\31\23\0\2\31\4\0\15\31\2\0\1\104"+
    "\4\31\1\u0141\23\31\23\0\2\52\4\0\15\52\2\0"+
    "\1\120\13\52\1\u0142\14\52\23\0\2\52\4\0\15\52"+
    "\2\0\1\120\22\52\1\u0143\5\52\23\0\2\52\4\0"+
    "\15\52\2\0\1\120\1\u0144\27\52\23\0\2\52\4\0"+
    "\15\52\2\0\1\120\1\u0145\27\52\23\0\2\52\4\0"+
    "\15\52\2\0\1\120\1\u0146\27\52\23\0\2\52\4\0"+
    "\15\52\2\0\1\120\20\52\1\u0147\7\52\23\0\2\52"+
    "\4\0\15\52\2\0\1\120\4\52\1\u0148\23\52\23\0"+
    "\2\31\4\0\15\31\2\0\1\104\20\31\1\u0149\7\31"+
    "\23\0\2\31\4\0\15\31\2\0\1\104\21\31\1\u014a"+
    "\6\31\23\0\2\52\4\0\15\52\2\0\1\120\4\52"+
    "\1\u014b\23\52\23\0\2\52\4\0\15\52\2\0\1\120"+
    "\4\52\1\u014c\23\52\23\0\2\52\4\0\15\52\2\0"+
    "\1\120\13\52\1\u014d\14\52\23\0\2\52\4\0\15\52"+
    "\2\0\1\120\20\52\1\u014e\7\52\23\0\2\52\4\0"+
    "\15\52\2\0\1\120\20\52\1\u014f\7\52\23\0\2\52"+
    "\4\0\15\52\2\0\1\120\21\52\1\u0150\6\52\23\0"+
    "\2\52\4\0\15\52\2\0\1\120\1\u0151\27\52\23\0"+
    "\2\52\4\0\15\52\2\0\1\120\20\52\1\u0152\7\52"+
    "\23\0\2\52\4\0\15\52\2\0\1\120\15\52\1\u0153"+
    "\12\52\23\0\2\52\4\0\15\52\2\0\1\120\16\52"+
    "\1\u0154\11\52\23\0\2\52\4\0\15\52\2\0\1\120"+
    "\16\52\1\u0155\11\52\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[17485];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\3\11\4\1\4\11\1\1\1\11\5\1\2\11"+
    "\1\1\1\11\12\1\2\11\21\1\1\11\1\1\1\0"+
    "\1\11\1\0\3\11\2\0\1\1\2\0\1\11\1\1"+
    "\1\0\43\1\1\11\1\0\1\1\2\0\1\11\52\1"+
    "\1\0\275\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[341];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
String contenido="";
    Boolean flag=true;
    private void ArchivoNuevo(){
        if(flag)
        {
            try {
                String ruta = "src/main/java/com/mycompany/proyectocompiladores/Salida.txt/";
                File file = new File(ruta);
                // Si el archivo no existe es creado
                if (!file.exists()) {
                    file.createNewFile();
                }
                FileWriter fw = new FileWriter(file);
                BufferedWriter bw = new BufferedWriter(fw);
                bw.write("");
                bw.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
            flag=false;
        }    
    }
    private void CrearArchivo(){
        ArchivoNuevo();
        try {
            String ruta = "src/main/java/com/mycompany/proyectocompiladores/Salida.txt/";
            File file = new File(ruta);
            // Si el archivo no existe es creado
            if (!file.exists()) {
                file.createNewFile();
            }
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.append(contenido+"\n");
            bw.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
public int tabulaciones;
public static ArrayList<Tablas> sim;

public void add(String nuevo) {
        boolean bandera = false;
        String a = nuevo;
       
        int numero = 0;
        if (sim.size() == 0) {
            Tablas sim2 = new Tablas();
            sim2.setCantidad(1);
            sim2.setValor(a);
            sim.add(sim2);
        } else {
            
            for (int x = 0; x < sim.size(); x++) {
                    
                Tablas sim1 = sim.get(x);

                if (sim1.getValor().equals(a)) {
                    bandera = true;
                    numero = x;

                    x = sim.size();
                } else {
                    bandera = false;
                }
            }

            if (bandera == true) {
               
                Tablas val = sim.get(numero);
                int n = val.getCantidad();
                n = n + 1;
                val.setCantidad(n);
                sim.remove(numero);
                sim.add(val);
                   
            } else {
              
                Tablas sim2 = new Tablas();
                sim2.setCantidad(1);
                sim2.setValor(a);
                sim.add(sim2);
            }
        }  
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Testeo(java.io.Reader in) {
      this.sim = new ArrayList<>();
    this.tabulaciones = 0;
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {   return new Symbol(sym.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.err.println("Error Léxico \"" + yytext() + "\" ["+"LINEA: "+ (yyline+1) + ": COLUMNA"+ (yycolumn+1) + "]");
            }
            // fall through
          case 75: break;
          case 2:
            { this.tabulaciones++;
            }
            // fall through
          case 76: break;
          case 3:
            { this.add("FIN DE LINEA");
            }
            // fall through
          case 77: break;
          case 4:
            { 
            }
            // fall through
          case 78: break;
          case 5:
            { this.add("MODULO");
            return new Symbol(sym.MODULO);
            }
            // fall through
          case 79: break;
          case 6:
            { this.add("PARENTESIS (");
            return new Symbol(sym.PARENTESIS1);
            }
            // fall through
          case 80: break;
          case 7:
            { this.add("PARENTESIS )");
            return new Symbol(sym.PARENTESIS2);
            }
            // fall through
          case 81: break;
          case 8:
            { this.add("MULTIPLICACION");
            return new Symbol(sym.MULTIPLICACION);
            }
            // fall through
          case 82: break;
          case 9:
            { this.add("SUMA");
           return new Symbol(sym.SUMA);
            }
            // fall through
          case 83: break;
          case 10:
            { this.add("COMA");
            return new Symbol(sym.COMA);
            }
            // fall through
          case 84: break;
          case 11:
            { this.add("RESTA");
            return new Symbol(sym.RESTA);
            }
            // fall through
          case 85: break;
          case 12:
            { this.add("PUNTO");
            return new Symbol(sym.SIGNOS);
            }
            // fall through
          case 86: break;
          case 13:
            { this.add("DIVISION");
            return new Symbol(sym.DIVISION);
            }
            // fall through
          case 87: break;
          case 14:
            { this.add("NUMEROS DECIMALES"); 
            return new Symbol(sym.NUMERO_DECIMAL);
            }
            // fall through
          case 88: break;
          case 15:
            { this.add("DOS PUNTOS");
            return new Symbol(sym.DOS_PUNTOS);
            }
            // fall through
          case 89: break;
          case 16:
            { this.add("MENOR QUE");
            return new Symbol(sym.SIGNOS);
            }
            // fall through
          case 90: break;
          case 17:
            { this.add("IGUAL");
            return new Symbol(sym.IGUAL);
            }
            // fall through
          case 91: break;
          case 18:
            { this.add("MAYOR QUE");
            return new Symbol(sym.SIGNOS);
            }
            // fall through
          case 92: break;
          case 19:
            { this.add("VARIABLE CLASE");
            return new Symbol(sym.VARIABLE_CLASE);
            }
            // fall through
          case 93: break;
          case 20:
            { this.add("TIPO BOOLEANO");
            }
            // fall through
          case 94: break;
          case 21:
            { this.add("CORCHETE 1");
           return new Symbol(sym.SIGNOS);
            }
            // fall through
          case 95: break;
          case 22:
            { this.add("CORCHETE 2");
            return new Symbol(sym.SIGNOS);
            }
            // fall through
          case 96: break;
          case 23:
            { this.add("VARIABLE"); 
            return new Symbol(sym.VARIABLE);
            }
            // fall through
          case 97: break;
          case 24:
            { this.add("DISTINTO QUE");
            return new Symbol(sym.SIGNOS);
            }
            // fall through
          case 98: break;
          case 25:
            { this.add("TIPO_DATO_CUP"); 
            return new Symbol(sym.CADENA);
            }
            // fall through
          case 99: break;
          case 26:
            { this.add("INCREMENTO");
            return new Symbol(sym.SIGNOS);
            }
            // fall through
          case 100: break;
          case 27:
            { this.add("DECREMENTO");
            return new Symbol(sym.SIGNOS);
            }
            // fall through
          case 101: break;
          case 28:
            { this.add("COMENTARIO");
            }
            // fall through
          case 102: break;
          case 29:
            { this.add("IGUAL QUE");
            return new Symbol(sym.SIGNOS);
            }
            // fall through
          case 103: break;
          case 30:
            { this.add("OR");
            return new Symbol(sym.SIGNOS);
            }
            // fall through
          case 104: break;
          case 31:
            { this.add("ERROR");
            }
            // fall through
          case 105: break;
          case 32:
            { this.add("IF");
            return new Symbol(sym.IF);
            }
            // fall through
          case 106: break;
          case 33:
            { this.add("EXPONENTE");
            return new Symbol(sym.SIGNOS);
            }
            // fall through
          case 107: break;
          case 34:
            { this.add("NUMEROS REALES");
            }
            // fall through
          case 108: break;
          case 35:
            { this.add("AND");
            return new Symbol(sym.SIGNOS);
            }
            // fall through
          case 109: break;
          case 36:
            { this.add("PAR O IMPAR");
          return new Symbol(sym.TIPO_DATO);
            }
            // fall through
          case 110: break;
          case 37:
            { this.add("LEER"); 
            return new Symbol(sym.LEER);
            }
            // fall through
          case 111: break;
          case 38:
            { this.add("TIPO NULO");
            }
            // fall through
          case 112: break;
          case 39:
            { this.add("RAIZ");
            return new Symbol(sym.FUNCION_ESPECIAL);
            }
            // fall through
          case 113: break;
          case 40:
            { this.add("TIPO REAL");
            return new Symbol(sym.TIPO_DATO);
            }
            // fall through
          case 114: break;
          case 41:
            { this.add("SENO");
            return new Symbol(sym.FUNCION_ESPECIAL);
            }
            // fall through
          case 115: break;
          case 42:
            { this.add("SINO");
            return new Symbol(sym.SINO);
            }
            // fall through
          case 116: break;
          case 43:
            { this.add("CLASE");
            return new Symbol(sym.CLASE);
            }
            // fall through
          case 117: break;
          case 44:
            { this.add("DESDE"); 
            return new Symbol(sym.DESDE);
            }
            // fall through
          case 118: break;
          case 45:
            { this.add("FALSO");
            return new Symbol(sym.FALSO);
            }
            // fall through
          case 119: break;
          case 46:
            { this.add("HACER"); 
            return new Symbol(sym.HACER);
            }
            // fall through
          case 120: break;
          case 47:
            { this.add("NUEVO");  
          return new Symbol(sym.NEW);
            }
            // fall through
          case 121: break;
          case 48:
            { this.add("TIPO CADENA");
            return new Symbol(sym.TIPO_DATO);
            }
            // fall through
          case 122: break;
          case 49:
            { this.add("COSENO");
            return new Symbol(sym.FUNCION_ESPECIAL);
            }
            // fall through
          case 123: break;
          case 50:
            { this.add("TIPO ENTERO");
            return new Symbol(sym.TIPO_DATO);
            }
            // fall through
          case 124: break;
          case 51:
            { this.add("METODOS");
            return new Symbol(sym.METODOS);
            }
            // fall through
          case 125: break;
          case 52:
            { this.add("TIPO DE PROPIEDAD");
            return new Symbol(sym.TIPO_DE_METODOS);
            }
            // fall through
          case 126: break;
          case 53:
            { this.add("INCLUIR");
            return new Symbol(sym.FUNCIONES_CLICLOS_ETC);
            }
            // fall through
          case 127: break;
          case 54:
            { this.add("METODO EJECUTAR");
           return new Symbol(sym.EJECUTAR);
            }
            // fall through
          case 128: break;
          case 55:
            { this.add("ELIMINAR"); 
            return new Symbol(sym.FUNCIONES_CLICLOS_ETC);
            }
            // fall through
          case 129: break;
          case 56:
            { this.add("TIPO BOOLEANO ");
          return new Symbol(sym.TIPO_DATO);
            }
            // fall through
          case 130: break;
          case 57:
            { this.add("DEVOLVER"); 
            return new Symbol(sym.DEVOLVER);
            }
            // fall through
          case 131: break;
          case 58:
            { this.add("ENCONCES"); 
            return new Symbol(sym.ENTONCES);
            }
            // fall through
          case 132: break;
          case 59:
            { this.add("ESCRIBIR"); 
            return new Symbol(sym.ESCRIBIR);
            }
            // fall through
          case 133: break;
          case 60:
            { this.add("EXTIENDE"); 
            return new Symbol(sym.FUNCIONES_CLICLOS_ETC);
            }
            // fall through
          case 134: break;
          case 61:
            { this.add("MIENTRAS"); 
            return new Symbol(sym.MIENTRAS);
            }
            // fall through
          case 135: break;
          case 62:
            { this.add("TANGENTE");
            return new Symbol(sym.FUNCION_ESPECIAL);
            }
            // fall through
          case 136: break;
          case 63:
            { this.add("PRINCIPAL"); 
            return new Symbol(sym.PRINCIPAL);
            }
            // fall through
          case 137: break;
          case 64:
            { this.add("LOGARTIMO");
            return new Symbol(sym.FUNCION_ESPECIAL);
            }
            // fall through
          case 138: break;
          case 65:
            { this.add("VERDADERO");
           return new Symbol(sym.VERDADERO);
            }
            // fall through
          case 139: break;
          case 66:
            { this.add("DESTRUCTOR"); 
            return new Symbol(sym.FUNCIONES_CLICLOS_ETC);
            }
            // fall through
          case 140: break;
          case 67:
            { this.add("INSTANCIAR"); 
            return new Symbol(sym.FUNCIONES_CLICLOS_ETC);
            }
            // fall through
          case 141: break;
          case 68:
            { this.add("CONSTRUCTOR"); 
            return new Symbol(sym.TIPO_DATO);
            }
            // fall through
          case 142: break;
          case 69:
            { this.add("PROPIEDADES"); 
            return new Symbol(sym.PROPIEDADES);
            }
            // fall through
          case 143: break;
          case 70:
            { this.add("CADENA:REAL");
            return new Symbol(sym.FUNCION_ESPECIAL);
            }
            // fall through
          case 144: break;
          case 71:
            { this.add("DECREMAR"); 
            return new Symbol(sym.DECREMENTAR);
            }
            // fall through
          case 145: break;
          case 72:
            { this.add("INCREMENTAR"); 
            return new Symbol(sym.INCREMENTAR);
            }
            // fall through
          case 146: break;
          case 73:
            { this.add("CADENA:ENTERO");
            return new Symbol(sym.FUNCION_ESPECIAL);
            }
            // fall through
          case 147: break;
          case 74:
            { this.add("CADENA:BOOLEANO");
            return new Symbol(sym.FUNCION_ESPECIAL);
            }
            // fall through
          case 148: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
