// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/main/java/com/mycompany/proyectocompiladores/Lexemas.flex

package com.mycompany.proyectocompiladores;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Test {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\12\0\1\1\2\2\1\3\24\0\1\4\2\0\1\5"+
    "\2\0\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\12\16\1\17\1\20\1\0\1\21\3\0\32\22"+
    "\6\0\1\23\1\24\1\25\1\26\1\27\3\22\1\30"+
    "\2\22\1\31\1\22\1\32\1\33\1\34\1\22\1\35"+
    "\1\36\1\37\1\40\1\41\4\22\12\0\1\2\u01a2\0"+
    "\2\2\326\0\u0100\2";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\1"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\10\15\2\0"+
    "\1\16\1\17\12\15\1\20\3\0\2\16\14\15\2\0"+
    "\1\16\10\15\1\21\3\15\1\20\1\0\1\15\1\22"+
    "\11\15\1\0\1\23\2\15\1\24\5\15\1\25\10\15"+
    "\1\26\1\15\1\27\5\15\1\30\1\31";

  private static int [] zzUnpackAction() {
    int [] result = new int[111];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\42\0\42\0\42\0\42\0\42\0\42\0\104"+
    "\0\42\0\42\0\146\0\42\0\42\0\42\0\210\0\252"+
    "\0\314\0\356\0\u0110\0\u0132\0\u0154\0\u0176\0\u0198\0\u01ba"+
    "\0\u01dc\0\u01fe\0\u0220\0\u0242\0\u0264\0\u0286\0\u02a8\0\u02ca"+
    "\0\u02ec\0\u030e\0\u0330\0\u0352\0\u0374\0\u0396\0\u03b8\0\u03da"+
    "\0\42\0\u03fc\0\u041e\0\u0440\0\u0462\0\u0484\0\u04a6\0\u04c8"+
    "\0\u04ea\0\u050c\0\u052e\0\u0550\0\u0572\0\u0594\0\u05b6\0\u05d8"+
    "\0\u03b8\0\u05fa\0\u061c\0\u063e\0\u0660\0\u0682\0\u06a4\0\u06c6"+
    "\0\u06e8\0\210\0\u070a\0\u072c\0\u074e\0\210\0\u0770\0\u0792"+
    "\0\210\0\u07b4\0\u07d6\0\u07f8\0\u081a\0\u083c\0\u085e\0\u0880"+
    "\0\u08a2\0\u08c4\0\u08e6\0\210\0\u0908\0\u092a\0\210\0\u094c"+
    "\0\u096e\0\u0990\0\u09b2\0\u09d4\0\42\0\u09f6\0\u0a18\0\u0a3a"+
    "\0\u0a5c\0\u0a7e\0\u0aa0\0\u0ac2\0\u0ae4\0\210\0\u0b06\0\210"+
    "\0\u0b28\0\u0b4a\0\u0b6c\0\u0b8e\0\u0bb0\0\210\0\210";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[111];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\3\3\1\4\1\5\1\6\1\7\1\2\1\10"+
    "\1\11\1\2\1\12\1\13\1\2\1\14\1\15\1\16"+
    "\3\17\1\20\1\21\1\22\1\23\1\24\2\17\1\25"+
    "\1\17\1\26\3\17\54\0\1\27\37\0\1\30\4\0"+
    "\1\31\42\0\1\32\3\0\20\17\16\0\1\32\3\0"+
    "\1\17\1\33\5\17\1\34\1\17\1\35\6\17\16\0"+
    "\1\32\3\0\5\17\1\36\12\17\16\0\1\32\3\0"+
    "\10\17\1\37\3\17\1\40\3\17\16\0\1\32\3\0"+
    "\10\17\1\41\7\17\16\0\1\32\3\0\5\17\1\42"+
    "\12\17\16\0\1\32\3\0\13\17\1\43\2\17\1\44"+
    "\1\17\16\0\1\32\3\0\6\17\1\45\11\17\15\0"+
    "\1\46\24\0\10\47\1\50\31\47\1\31\1\51\1\31"+
    "\1\52\36\31\16\0\1\32\3\0\20\32\16\0\1\32"+
    "\3\0\4\17\1\53\13\17\16\0\1\32\3\0\1\17"+
    "\1\54\16\17\16\0\1\32\3\0\10\17\1\55\7\17"+
    "\16\0\1\32\3\0\17\17\1\56\16\0\1\32\3\0"+
    "\15\17\1\57\2\17\16\0\1\32\3\0\3\17\1\60"+
    "\14\17\16\0\1\32\3\0\14\17\1\61\3\17\16\0"+
    "\1\32\3\0\5\17\1\62\12\17\16\0\1\32\3\0"+
    "\6\17\1\63\2\17\1\64\6\17\16\0\1\32\3\0"+
    "\2\17\1\65\15\17\16\0\1\32\3\0\10\17\1\66"+
    "\7\17\12\0\1\67\27\0\10\47\1\70\41\47\1\70"+
    "\4\47\1\71\24\47\1\0\1\51\56\0\1\32\3\0"+
    "\5\17\1\72\12\17\16\0\1\32\3\0\14\17\1\73"+
    "\3\17\16\0\1\32\3\0\14\17\1\74\3\17\16\0"+
    "\1\32\3\0\11\17\1\75\6\17\16\0\1\32\3\0"+
    "\5\17\1\76\3\17\1\77\6\17\16\0\1\32\3\0"+
    "\13\17\1\100\4\17\16\0\1\32\3\0\15\17\1\101"+
    "\2\17\16\0\1\32\3\0\13\17\1\102\4\17\16\0"+
    "\1\32\3\0\17\17\1\103\16\0\1\32\3\0\12\17"+
    "\1\104\5\17\16\0\1\32\3\0\7\17\1\105\10\17"+
    "\16\0\1\32\3\0\11\17\1\106\6\17\13\0\1\107"+
    "\26\0\10\47\1\70\4\47\1\51\24\47\16\0\1\32"+
    "\3\0\10\17\1\110\7\17\16\0\1\32\3\0\5\17"+
    "\1\111\12\17\16\0\1\32\3\0\15\17\1\112\2\17"+
    "\16\0\1\32\3\0\7\17\1\113\10\17\16\0\1\32"+
    "\3\0\13\17\1\114\4\17\16\0\1\32\3\0\10\17"+
    "\1\115\7\17\16\0\1\32\3\0\6\17\1\116\11\17"+
    "\16\0\1\32\3\0\1\17\1\117\16\17\16\0\1\32"+
    "\3\0\1\17\1\120\16\17\16\0\1\32\3\0\6\17"+
    "\1\121\11\17\16\0\1\32\3\0\6\17\1\122\11\17"+
    "\12\0\1\123\45\0\1\32\3\0\1\17\1\124\16\17"+
    "\16\0\1\32\3\0\13\17\1\125\4\17\16\0\1\32"+
    "\3\0\17\17\1\126\16\0\1\32\3\0\11\17\1\127"+
    "\6\17\16\0\1\32\3\0\3\17\1\130\14\17\16\0"+
    "\1\32\3\0\2\17\1\131\15\17\16\0\1\32\3\0"+
    "\10\17\1\132\7\17\16\0\1\32\3\0\4\17\1\133"+
    "\13\17\16\0\1\32\3\0\5\17\1\134\12\17\16\0"+
    "\1\32\3\0\3\17\1\133\14\17\10\0\1\135\47\0"+
    "\1\32\3\0\16\17\1\136\1\17\16\0\1\32\3\0"+
    "\5\17\1\137\12\17\16\0\1\32\3\0\5\17\1\140"+
    "\12\17\16\0\1\32\3\0\6\17\1\141\11\17\16\0"+
    "\1\32\3\0\3\17\1\142\14\17\16\0\1\32\3\0"+
    "\1\17\1\143\7\17\1\143\6\17\16\0\1\32\3\0"+
    "\4\17\1\144\13\17\16\0\1\32\3\0\3\17\1\145"+
    "\14\17\16\0\1\32\3\0\13\17\1\106\4\17\16\0"+
    "\1\32\3\0\14\17\1\106\3\17\16\0\1\32\3\0"+
    "\13\17\1\146\4\17\16\0\1\32\3\0\6\17\1\147"+
    "\11\17\16\0\1\32\3\0\14\17\1\150\3\17\16\0"+
    "\1\32\3\0\1\17\1\151\16\17\16\0\1\32\3\0"+
    "\15\17\1\152\2\17\16\0\1\32\3\0\1\17\1\153"+
    "\16\17\16\0\1\32\3\0\4\17\1\154\13\17\16\0"+
    "\1\32\3\0\11\17\1\155\6\17\16\0\1\32\3\0"+
    "\13\17\1\156\4\17\16\0\1\32\3\0\5\17\1\143"+
    "\12\17\16\0\1\32\3\0\13\17\1\157\4\17";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3026];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\6\11\1\1\2\11\1\1\3\11\10\1\2\0"+
    "\15\1\3\0\1\11\15\1\2\0\16\1\1\0\13\1"+
    "\1\0\11\1\1\11\22\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[111];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    String contenido="";
    Boolean flag=true;
    private void ArchivoNuevo(){
        if(flag)
        {
            try {
                String ruta = "src/main/java/com/mycompany/proyectocompiladores/Salida.txt/";
                File file = new File(ruta);
                // Si el archivo no existe es creado
                if (!file.exists()) {
                    file.createNewFile();
                }
                FileWriter fw = new FileWriter(file);
                BufferedWriter bw = new BufferedWriter(fw);
                bw.write("");
                bw.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
            flag=false;
        }    
    }
    private void CrearArchivo(){
        ArchivoNuevo();
        try {
            String ruta = "src/main/java/com/mycompany/proyectocompiladores/Salida.txt/";
            File file = new File(ruta);
            // Si el archivo no existe es creado
            if (!file.exists()) {
                file.createNewFile();
            }
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.append(contenido+"\n");
            bw.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Test(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { 
            }
            // fall through
          case 26: break;
          case 2:
            { System.out.print(yytext());
            }
            // fall through
          case 27: break;
          case 3:
            { System.out.println("Encontré comillas: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn);
            contenido=contenido+"Encontré comillas: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn+"\n";
            CrearArchivo();
            }
            // fall through
          case 28: break;
          case 4:
            { System.out.println("Encontré un porcentaje: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn);
            contenido=contenido+"Encontré un porcentaje: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn+"\n";
            CrearArchivo();
            }
            // fall through
          case 29: break;
          case 5:
            { System.out.println("Encontré un parentesis de abertura: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn);
            contenido=contenido+"Encontré un parentesis de abertura: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn+"\n";
            CrearArchivo();
            }
            // fall through
          case 30: break;
          case 6:
            { System.out.println("Encontré un parentesis de cierre: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn);
            contenido=contenido+"Encontré un parentesis de cierre: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn+"\n";
            CrearArchivo();
            }
            // fall through
          case 31: break;
          case 7:
            { System.out.println("Encontré un coma: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn);
            contenido=contenido+"Encontré un coma: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn+"\n";
            CrearArchivo();
            }
            // fall through
          case 32: break;
          case 8:
            { System.out.println("Encontré un punto: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn);
            contenido=contenido+"Encontré un punto: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn+"\n";
            CrearArchivo();
            }
            // fall through
          case 33: break;
          case 9:
            { System.out.println("Encontré una barra: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn);
            contenido=contenido+"Encontré una barra: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn+"\n";
            CrearArchivo();
            }
            // fall through
          case 34: break;
          case 10:
            { System.out.println("Encontré un dos puntos: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn);
            contenido=contenido+"Encontré un dos puntos: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn+"\n";
            CrearArchivo();
            }
            // fall through
          case 35: break;
          case 11:
            { System.out.println("Encontré un punto y coma: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn);
            contenido=contenido+"Encontré un punto y coma: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn+"\n";
            CrearArchivo();
            }
            // fall through
          case 36: break;
          case 12:
            { System.out.println("Encontré un signo: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn);
            contenido=contenido+"Encontré un signo: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn+"\n";
            CrearArchivo();
            }
            // fall through
          case 37: break;
          case 13:
            { System.out.println("Encontré letras: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn);
            contenido=contenido+"Encontré letras: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn+"\n";
            CrearArchivo();
            }
            // fall through
          case 38: break;
          case 14:
            { System.out.println("Encontré un comentario: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn);
            contenido=contenido+"Encontré un comentario: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn+"\n";
            CrearArchivo();
            }
            // fall through
          case 39: break;
          case 15:
            { System.out.println("Encontré un variable: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn);
            contenido=contenido+"Encontré un variable: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn+"\n";
            CrearArchivo();
            }
            // fall through
          case 40: break;
          case 16:
            { System.out.println("Encontré una sentencia: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn);
            contenido=contenido+"Encontré una sentencia: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn+"\n";
            CrearArchivo();
            }
            // fall through
          case 41: break;
          case 17:
            { System.out.println("Encontré un leer: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn);
            contenido=contenido+"Encontré un leer: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn+"\n";
            CrearArchivo();
            }
            // fall through
          case 42: break;
          case 18:
            { System.out.println("Encontré un clase: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn);
            contenido=contenido+"Encontré un clase: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn+"\n";
            CrearArchivo();
            }
            // fall through
          case 43: break;
          case 19:
            { System.out.println("Encontré una Cadena:  "+yytext()+" en linea: "+yyline+" columna: "+yycolumn);
            contenido=contenido+"Encontré una Cadena:  "+yytext()+" en linea: "+yyline+" columna: "+yycolumn+"\n";
            CrearArchivo();
            }
            // fall through
          case 44: break;
          case 20:
            { System.out.println("Encontré un numero: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn);
            contenido=contenido+"Encontré un numero: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn+"\n";
            CrearArchivo();
            }
            // fall through
          case 45: break;
          case 21:
            { System.out.println("Encontré un signo Matematico: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn);
            contenido=contenido+"Encontré un signo Matematico: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn+"\n";
            CrearArchivo();
            }
            // fall through
          case 46: break;
          case 22:
            { System.out.println("Encontré un escribir: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn);
            contenido=contenido+"Encontré un escribir: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn+"\n";
            CrearArchivo();
            }
            // fall through
          case 47: break;
          case 23:
            { System.out.println("Encontré que es tipo: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn);
            contenido=contenido+"Encontré que es tipo: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn+"\n";
            CrearArchivo();
            }
            // fall through
          case 48: break;
          case 24:
            { System.out.println("Encontré un instanciar: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn);
            contenido=contenido+"Encontré un instanciar: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn+"\n";
            CrearArchivo();
            }
            // fall through
          case 49: break;
          case 25:
            { System.out.println("Encontré un constructor: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn);
            contenido=contenido+"Encontré un constructor: "+yytext()+" en linea: "+yyline+" columna: "+yycolumn+"\n";
            CrearArchivo();
            }
            // fall through
          case 50: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String[] argv) {
    if (argv.length == 0) {
      System.out.println("Usage : java Test [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Test scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Test(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
